#%RAML 1.0 DataType
type: object
properties:
  tngCrsTypCd:  
    type: string 
    required: false 
  locCd:  
    type: string 
    required: false 
  date:  
    type: date-only 
    required: false 
  uic:  
    type: string 
    required: false 
  course:  
    type: string 
    required: true 
  classNbr:  
    type: number 
    required: false
