#%RAML 1.0 DataType
description: enlistConfirmReasons 
type: object
#examples:
  #output: !include ../examples/posnIdExample.raml
properties:
    enlistConfirmReasons:
      type: array
      required: false