#%RAML 1.0 DataType
description: sciAccredCd
type: object
examples:
  output: !include ../examples/sciAccredCdExample.raml
#examples:
  #output: !include ../examples/posnIdExample.raml
properties:
    sciAccredCd:
      type: array
      required: true