#%RAML 1.0 NamedExample
value:
  "indSsn": "000345521"
  "indivName": !include indivNameExample.raml
  "indAddr": !include indAddrExample.raml
  "indEmail": "scott.d.malinowski@mail.mil"
  "indPhoneNr": !include indPhoneNrExample.raml
  "citizenshipStat": "C"
  "citizenship": "A"
  "birthCtryCd": "US"
  "indSexCd": "U"
  "indRacePopCd": "C"
  "indEthnicCd": "Y"
  "indOpLic": "111222333"
  "indOpLicExpDt": "2016-12-31T00:00:00"
  "birthDt": "1998-01-01T00:00:00"
  "nbrAdultDep": "1"
  "nbrChildDep": "2"
  "rctgProgCd" :  ["T4"]
  "svc": "R"
  "statOblig": "N"
  "enlistCatCd": "NPS"
  "starrPartCd" : "N"
  "mpc": "E"
  "payLevel": "1"
  "enlType": "5"
  "BasActSvcDt": "2016-08-01"
  "recruiterSSN": "000143999"
  "rsid": "8T4A"
  "consObj": "A1"
  "vol": "Y"
  "secClr": "Y"
  "inducteeCd": "N"
  "mepsId": "A01"
  "advRankRsn": "2"
  "prspctRecInd": "123456789"
  "officeCd": "8T"
  "missionBoxCat": "MBOX"
  "ttasScore": 87
  "ttasPassInd": "Y"
  "blueToGreenPart": "N"
  "enlistConfirm": "Y"
  "enlistConfirmReasons": ["CL"]
  "shipConfirmReasons": ["CL"]
  "physicalProf": "111111"
  "mepsCat": "E"
  "cp": "N"
  "height": 72
  "weight": 160
  "physicalExam": !include physicalExamExample.raml
  "bmi": 15
  "educYrs": 12
  "educCd": "L"
  "asvabResults": !include asvabResultsExample.raml
  "mathAccredCd": "1"
  "sciAccredCd": "1"
  "apftDt": "2016-07-15"
  "apftPassInd": "P"
  "typingCertInd": "Y"
  "typingWPM": 74
  "bandScore": 2.25
  "bandDate": "2016-07-15"
  "voiceScore": "P"
  "voiceDate": "2016-07-15"
  "testResults": [!include testResultsExample.raml]
  "gcSSN": "000143998"
  "basicTrCmpt": "Y"
   
  
