#%RAML 1.0 NamedExample
value:
  "testDt": "2016-08-01"
  "afqt": 97
  "gt": 95
  "gm": 99
  "el": 100
  "cl": 105
  "mm": 98
  "sc": 88
  "co": 99
  "fa": 101
  "of": 100
  "st": 110
  "gsRaw": 55
  "arRaw": 56
  "wkRaw": 57
  "pcRaw": 58
  "aoRaw": 54
  "asRaw": 61
  "mkRaw": 59
  "mcRaw": 62
  "elRaw": 60
  "veRaw": 64
