#%RAML 1.0 NamedExample
"enlistConfirmReasonsExample":  [
      "Missing required document: DD 4.", "Missing required document: DD 1966.", "Missing required document: DD 93.", "Missing required document: Reserves Annex A."]