#%RAML 1.0 NamedExample
testResults: 
-
 testType: "AIM"
 testDt: "2016-06-01"
 score: 87
-
 testType: "SWPT"
 testDt: "2016-06-01"
 score: 99
-
 testType: "SAT"
 testDt: "2016-06-01"
 score: 150
-
 testType: "AAT"
 testDt: "2016-06-01"
 score: 65
-
 testType: "AP"
 testDt: "2016-06-01"
 score: 55
-
 testType: "ECLT"
 testDt: "2016-06-01"
 score: 77
-
 testType: "OP"
 testDt: "2016-06-01"
 score: 2
