#%RAML 1.0 NamedExample
value:
  code: '500'
  message: Iternal Server Error
  status: INTERNAL
  sender: College Testing
  receiver: AIE
  notification: avula_vasu@bah.com
  epochTime: 1123456
  details:
  - uuid: 1111ABC
    type: java.util.ArrayIndexExceeded
    message: You exceeded the array index bounds.